name: flutter_webview_full_slides
description: Full WebView workshop code from slides
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/index.html
    - assets/cart.html
    - assets/challenge_webview.html
